version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Test command!
          command: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
